### ISSUE TITLE
Collection linter

### ISSUE THREAD

**Issue by petemounce** [viglesiasce/kube-lint#7]
I'd like to be able to lint my configuration to prevent a service from being configured that has more than one port defined for the same port with the same protocol.

e.g. prevent

```yaml
apiVersion: v1
kind: Service
...
spec:
  ...
  ports:
  - name: foo
    port: 10104
    targetPort: 10104
    protocol: TCP
  - name: bar
    port: 10104
    targetPort: 10104
    protocol: TCP
```
